# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.10.0.schema.json
PackageIdentifier: TechToolbox.TechShell
PackageVersion: 1.0.18
PackageLocale: en-US
Publisher: Open Source Developer Daniel Damit
PackageName: TechShell
License: MIT
ShortDescription: TechToolbox Windows shell experience.
ManifestType: defaultLocale
ManifestVersion: 1.10.0

