# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json
PackageIdentifier: TechToolbox.TechShell
PackageVersion: 1.0.18
MinimumOSVersion: 10.0.17763.0
Installers:
  - Architecture: x64
    InstallerType: msix
    Scope: machine
    PackageFamilyName: C7E250C2-5AB3-4BD6-8DD7-14708E00A38B_zb2d6w29f13w6
    InstallerUrl: https://github.com/dan-damit/TechToolbox/releases/download/techshell-v1.0.18/TechShell.msix
    InstallerSha256: EFE89BBC866378C037BAB4BE3F4E35D3B2FF4B7EF8F942B11AE3CA98F1DC1384
ManifestType: installer
ManifestVersion: 1.10.0

