# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json
PackageIdentifier: TechToolbox.TechShell
PackageVersion: 1.0.18
MinimumOSVersion: 10.0.17763.0
Installers:
  - Architecture: x64
    InstallerType: msix
    Scope: machine
    PackageFamilyName: C7E250C2-5AB3-4BD6-8DD7-14708E00A38B_zb2d6w29f13w6
    InstallerUrl: https://github.com/dan-damit/TechToolbox/releases/download/techshell-v1.0.18/TechShell.msix
    InstallerSha256: E0EC2B751A70F3CA97A8CC1773946A0E54F7A96FB7E33AB423371D55C6EA5236
ManifestType: installer
ManifestVersion: 1.10.0

