# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json
PackageIdentifier: TechToolbox.TechShell
PackageVersion: 1.0.18
MinimumOSVersion: 10.0.17763.0
Installers:
  - Architecture: x64
    InstallerType: msix
    Scope: machine
    PackageFamilyName: C7E250C2-5AB3-4BD6-8DD7-14708E00A38B_zb2d6w29f13w6
    InstallerUrl: https://github.com/dan-damit/TechToolbox/releases/download/techshell-v1.0.18/TechShell.msix
    InstallerSha256: C58DD3FFF06D848D0F7B0719B6A3163802A3FC29C7B1DE0909C99FBF2340BB02
ManifestType: installer
ManifestVersion: 1.10.0

