# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.10.0.schema.json
PackageIdentifier: TechToolbox.TechShell
PackageVersion: 1.0.17
PackageLocale: en-US
Publisher: VADTEK
PackageName: TechShell
License: MIT
ShortDescription: TechToolbox Windows shell experience.
ManifestType: defaultLocale
ManifestVersion: 1.10.0

